import { ImageSourcePropType } from 'react-native';

// PNG art for base decorations, keyed by the decor id in src/state/base.ts.
// When an id has an entry here, BaseScreen renders the image; otherwise it
// falls back to the emoji glyph from the catalog. Drop transparent PNGs into
// assets/base/<id>.png (square, ~64x64 for the 1x1 items) to replace the
// placeholders.
export const DECOR_ART: Record<string, ImageSourcePropType> = {
  rock: require('../../assets/base/rock.png'),
  bush: require('../../assets/base/bush.png'),
  bowl: require('../../assets/base/bowl.png'),
  ball: require('../../assets/base/ball.png'),
  flowers: require('../../assets/base/flowers.png'),
  tree: require('../../assets/base/tree.png'),
  lamp: require('../../assets/base/lamp.png'),
  bed: require('../../assets/base/bed.png'),
  pond: require('../../assets/base/pond.png'),
};

export const decorArt = (id: string): ImageSourcePropType | undefined =>
  DECOR_ART[id];

// Auto-tiling wall sprites, keyed by neighbour bitmask (see wallMask in
// src/state/base.ts). Generated by scripts/gen-walls.mjs.
export const WALL_ART: Record<number, ImageSourcePropType> = {
  0: require('../../assets/base/wall_0.png'),
  1: require('../../assets/base/wall_1.png'),
  2: require('../../assets/base/wall_2.png'),
  3: require('../../assets/base/wall_3.png'),
  4: require('../../assets/base/wall_4.png'),
  5: require('../../assets/base/wall_5.png'),
  6: require('../../assets/base/wall_6.png'),
  7: require('../../assets/base/wall_7.png'),
  8: require('../../assets/base/wall_8.png'),
  9: require('../../assets/base/wall_9.png'),
  10: require('../../assets/base/wall_10.png'),
  11: require('../../assets/base/wall_11.png'),
  12: require('../../assets/base/wall_12.png'),
  13: require('../../assets/base/wall_13.png'),
  14: require('../../assets/base/wall_14.png'),
  15: require('../../assets/base/wall_15.png'),
};

export const wallArt = (mask: number): ImageSourcePropType | undefined =>
  WALL_ART[mask];

// PNG art for Phase 2 buildings, keyed by building id in src/state/base.ts.
// Falls back to the catalog glyph when an id is missing (same pattern as decor).
export const BUILDING_ART: Record<string, ImageSourcePropType> = {
  mine: require('../../assets/base/mine.png'),
  incubator: require('../../assets/base/incubator.png'),
  feeder: require('../../assets/base/feeder.png'),
  vault: require('../../assets/base/vault.png'),
};

export const buildingArt = (id: string): ImageSourcePropType | undefined =>
  BUILDING_ART[id];
